import { RenderMode } from '@angular/ssr';
import { describe, expect, it } from 'vitest';

import { SUPPORTED_LOCALES } from '@ui';

import { routes } from './app.routes';
import { serverRoutes } from './app.routes.server';

describe('ng-tag-build routes', () => {
  it('keeps the direct app route for the real tool page', () => {
    expect(routes.some((route) => route.path === 'app')).toBe(true);
    expect(routes.at(-1)?.path).toBe('**');
  });

  it('accepts locale-prefixed app routes generated by local navigation links', () => {
    for (const { urlSegment } of SUPPORTED_LOCALES) {
      const localeRoute = routes.find((route) => route.path === urlSegment);

      expect(localeRoute).toBeTruthy();
      expect(localeRoute?.children?.some((route) => route.path === '')).toBe(
        true
      );
      expect(localeRoute?.children?.some((route) => route.path === 'app')).toBe(
        true
      );
      expect(
        localeRoute?.children?.some((route) => route.path === 'about')
      ).toBe(true);
      expect(
        localeRoute?.children?.some((route) => route.path === 'objectives')
      ).toBe(true);
    }
  });

  it('marks locale-prefixed app URLs as client-rendered server routes', () => {
    const clientRoutes = getServerPaths(RenderMode.Client);

    expect(clientRoutes).toContain('app');
    for (const { urlSegment } of SUPPORTED_LOCALES) {
      expect(clientRoutes).toContain(`${urlSegment}/app`);
    }
  });

  it('keeps landing, about, and objectives prerenderable for direct and localized URLs', () => {
    const prerenderRoutes = getServerPaths(RenderMode.Prerender);

    expect(prerenderRoutes).toEqual(
      expect.arrayContaining(['', 'about', 'objectives'])
    );

    for (const { urlSegment } of SUPPORTED_LOCALES) {
      expect(prerenderRoutes).toEqual(
        expect.arrayContaining([
          urlSegment,
          `${urlSegment}/about`,
          `${urlSegment}/objectives`
        ])
      );
    }
  });
});

function getServerPaths(renderMode: RenderMode): string[] {
  return serverRoutes
    .filter((route) => route.renderMode === renderMode)
    .map((route) => route.path);
}
