packages:
  - apps/**
  - libs/**

allowBuilds:
  '@firebase/util': true
  '@nestjs/core': true
  '@parcel/watcher': true
  '@scarf/scarf': true
  '@swc/core': true
  esbuild: true
  ffmpeg-static: true
  less: true
  lmdb: true
  msgpackr-extract: true
  nx: true
  protobufjs: true
  puppeteer: true
  puppeteer-chromium-resolver: true
  sqlite3: true
  unrs-resolver: true

onlyBuiltDependencies:
  - '@firebase/util'
  - '@nestjs/core'
  - '@parcel/watcher'
  - '@scarf/scarf'
  - '@swc/core'
  - core-js
  - core-js-pure
  - esbuild
  - ffmpeg-static
  - less
  - lmdb
  - msgpackr-extract
  - nx
  - protobufjs
  - puppeteer
  - puppeteer-chromium-resolver
  - sqlite3
  - tag-check
  - unrs-resolver
