export enum VariableTypeEnum {
  CONSTANT = 'c',
  DATA_LAYER = 'v',
  REGEX = 'remm',
  EVENT_SETTINGS = 'gtes',
  SCROLL_DEPTH_THRESHOLD = 'SCROLL_DEPTH_THRESHOLD',
  VIDEO_PROVIDER = 'VIDEO_PROVIDER',
  VIDEO_URL = 'VIDEO_URL',
  VIDEO_TITLE = 'VIDEO_TITLE',
  VIDEO_DURATION = 'VIDEO_DURATION',
  VIDEO_PERCENT = 'VIDEO_PERCENT',
  VIDEO_VISIBLE = 'VIDEO_VISIBLE',
  VIDEO_STATUS = 'VIDEO_STATUS',
  VIDEO_CURRENT_TIME = 'VIDEO_CURRENT_TIME'
}
