name: Build
on:
  push:
    branches: [main, develop]
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  sonarcloud:
    name: SonarCloud
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Shallow clones should be disabled for a better relevancy of analysis
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '24.x'
      - name: Setup pnpm
        run: |
          corepack enable
          corepack prepare pnpm@11.0.8 --activate
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Backend integration tests
        run: pnpm run test-back:integration
        shell: bash
      - name: Test and coverage
        run: pnpm run test:cov
        shell: bash
      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage/lcov.info
      - name: SonarCloud Scan
        uses: SonarSource/sonarqube-scan-action@v6
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
